@startuml Tabacaria
'========Produto========='
class Produto{
    - id: Long
    - nome: String
    - descricao: String
    - preco: Double
    - qtdNoEstoque: Integer
}

class Arma{
    - tipoMunicao: String
    - peso: Double
    - rna: String
}

enum TipoArma{
    REVOLVER,
    PISTOLA,
    ESPINGARDA,
    RIFLE,
    CARABINA,
    METRALHADORA;

    - id: Long
    - label: String
}

'========Usuario========='
class Usuario{
    - id: Long
    - login: String
    - senha: String
}

enum Perfil{
    USER, 
    ADMIN;

    - id: Long
    - label: String
}

class Funcionario{
    - id: Long
    - nome: String
    - matricula: String
    - email: String
    - telefone: String
    - cpf: String
}

class Pessoa{
    - id: Long
    - nome: String
    - cpf: String
    - email: String
    - listaTelefone: List<String>
}
'========Venda========='
class Pedido {
    - id: Long
    - data: Date
    - totalCompra: Double
}

class ItemPedido {
    - id: Long
    - quantidade: Integer
    - preco: Double
}

enum Status{
    PROCESSANDO, 
    ACEITO,
    RECUSADO,
    EM TRASNSITO,
    ENTREGUE;

    - id: Long
    - label: String
}
'========Pagamento========='
class Pagamento{
    - id: Long
    - data: Date
}

class Cartao{
    - id: Long
    - numero: String
    - dataVencimento: Date
    - codVerificacao: String
    - nomeTitular: String
}

enum TipoCartao{
    CREDITO, 
    DEBITO, 
    CREDITO E DEBITO;

    - id: Long
    - label: String 
}

enum TipoPagamento {
    CREDITO, 
    DEBITO;

    - id: Long
    - label: String 
}

enum BandeiraCartao {
    VISA,
    ELO,
    MASTERCARD;

    - id: Long
    - label: String 
}
'========Endereco========='
class Endereco {
    - id: Long
    - principal: Boolean
    - logradouro: String
    - bairro: String
    - numero: String
    - complemento: String
    - cep: String
    - cidade: String
    - estado: String
}

'========Relacionamentos========='

Pedido "1" --> "1" Pagamento
Pedido "1" --> "*" ItemPedido
Pedido "1" --> "1" Status
Pedido "*" --> "1" Usuario
Pedido "*" --> "1" Endereco

Pagamento "1" --> "1" Status
Pagamento "1" --> "1" Cartao
Pagamento "1" --> "1" TipoPagamento

Cartao "1" --> "1" TipoCartao
Cartao "1" --> "1" BandeiraCartao

ItemPedido "*" --> "1" Produto

Usuario "1" --> "1" Perfil
Pessoa "1" --> "1" Usuario
Pessoa "1" --> "*" Endereco
Pessoa "1" --> "*" Cartao
Funcionario "1" --> "1" Usuario

Arma --|> Produto
Arma "1" --> "1" TipoArma
@enduml