@startuml Tabacaria
'========Produto========='
class Produto{
    - id: Long
    - nome: String
    - descricao: String
    - preco: Double
    - valor: Double
    - qtdNoEstoque: Integer
}

class Arma{
    - tipoMunicao: String
    - peso: Double
}

enum TipoArma{
    REVOLVER,
    PISTOLA,
    ESPINGARDA,
    RIFLE,
    CARABINA,
    METRALHADORA;

    - id: Long
    - label: String
}

'========Usuario========='
class Usuario{
    - id: Long
    - login: String
    - senha: String
}

enum Perfil{
    CLIENTE,
    FUNCIONARIO, 
    ADMIN;

    - id: Long
    - label: String
}

class Pessoa{
    - id: Long
    - nome: String
    - email: String
    - telefone: String
}

'Registro Nacional de Armas (RNA)'
class PessoaFisica{
    - cpf: String
    - RegistroMilitar: String 
}

class PessoaJuridica{
    - cnpj: String
}
'========Venda========='
class Pedido {
    - id: Long
    - data: Date
    - totalCompra: Double
}

class ItemPedido {
    - id: Long
    - quantidade: Integer
    - preco: Double
}

enum Status{
    PROCESSANDO, 
    ACEITA,
    RECUSADA,
    EM TRASNSITO,
    ENTREGUE;

    - id: Long
    - label: String
}
'========Pagamento========='
class Pagamento{
    - id: Long
}

class Cartao{
    - id: Long
    - numero: String
    - dataVencimento: Date
    - codVerificacao: int
    - nomeTitular: String
}

enum TipoCartao{
    CREDITO, 
    DEBITO, 
    CREDITO E DEBITO;

    - id: Long
    - label: String 
}

enum TipoPagamento {
    CREDITO, 
    DEBITO;

    - id: Long
    - label: String 
}

enum BandeiraCartao {
    VISA,
    ELO,
    MASTERCARD;

    - id: Long
    - label: String 
}
'========Endereco========='
class Endereco {
    - id: Long
    - principal: Boolean
    - logradouro: String
    - bairro: String
    - numero: String
    - complemento: String
    - cep: String
    - cidade: String
    - estado: String
}

'========Relacionamentos========='

Pedido "1" *--> "1" Pagamento
Pedido "1" *--> "*" ItemPedido
Pedido "1" *--> "1" Status
Pedido "*" --> "1" Usuario
Pedido "*" --> "1" Endereco

Pagamento "1" --> "1" Status
Pagamento "1" --> "1" Cartao
Pagamento "1" --> "1" TipoPagamento

Cartao "1" --> "1" TipoCartao
Cartao "1" --> "1" BandeiraCartao

ItemPedido "*" --> "1" Produto

Usuario "1" --> "1" Perfil
Usuario "1" --> "1" Pessoa : "Dados Pessoais"
Pessoa "1" *--> "1" Endereco
Pessoa "1" --> "*" Cartao

PessoaFisica --|> Pessoa
PessoaJuridica --|> Pessoa

Arma --|> Produto
Arma "1" --> "1" TipoArma
@enduml